import image1 from "../../../images/pro-sonjoy.png";

export const productData = [
  {
    id: 1,
    name: "Marketing Templates demo 2",
    description: "Email, newsletter and landing page templates.",
    image: image1,
    teg: ["Newest , Latest , Bestsellers"],
  },
  {
    id: 2,
    name: "Marketing Templates",
    description:
      "Email, newsletter and landing page templates. Email, newsletter and landing page templates. Email, newsletter and landing page templates.",
    image: image1,
    teg: ["Newest , Latest , Bestsellers"],
  },
  {
    id: 3,
    name: "Marketing Templates",
    description: "Email, newsletter and landing page templates.",
    image: image1,
    teg: ["Newest , Latest , Bestsellers"],
  },
  {
    id: 4,
    name: "Marketing Templates",
    description: "Email, newsletter and landing page templates.",
    image: image1,
    teg: ["Newest , Latest , Bestsellers"],
  },
  {
    id: 5,
    name: "Marketing Templates",
    description: "Email, newsletter and landing page templates.",
    image: image1,
    teg: ["Newest , Latest , Bestsellers"],
  },
  {
    id: 6,
    name: "Marketing Templates",
    description: "Email, newsletter and landing page templates.",
    image: image1,
    teg: ["Newest , Latest , Bestsellers"],
  },
  {
    id: 7,
    name: "Marketing Templates",
    description: "Email, newsletter and landing page templates.",
    image: image1,
    teg: ["Newest , Latest , Bestsellers"],
  },
  {
    id: 8,
    name: "Marketing Templates",
    description: "Email, newsletter and landing page templates.",
    image: image1,
    teg: ["Newest , Latest , Bestsellers"],
  },
  {
    id: 9,
    name: "Marketing Templates",
    description: "Email, newsletter and landing page templates.",
    image: image1,
    teg: ["Newest , Latest , Bestsellers"],
  },
  {
    id: 10,
    name: "Marketing Templates",
    description: "Email, newsletter and landing page templates.",
    image: image1,
    teg: ["Newest , Latest , Bestsellers"],
  },
  {
    id: 11,
    name: "Marketing Templates",
    description: "Email, newsletter and landing page templates.",
    image: image1,
    teg: ["Newest , Latest , Bestsellers"],
  },
  {
    id: 12,
    name: "Marketing Templates",
    description: "Email, newsletter and landing page templates.",
    image: image1,
    teg: ["Newest , Latest , Bestsellers"],
  },
  {
    id: 13,
    name: "Marketing Templates",
    description: "Email, newsletter and landing page templates.",
    image: image1,
    teg: ["Newest , Latest , Bestsellers"],
  },
];
